apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynamic-label-controller-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynamic-label-controller-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: controller-sa
  namespace: default
roleRef:
  kind: Role
  name: dynamic-label-controller-role
  apiGroup: rbac.authorization.k8s.io
